/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
(see esbuild.config.mjs / src/main.ts in the institute-one repo)
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  default: () => InstituteOnePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");
var DEFAULT_TIMEOUT_MS = 1e4;
var ASK_TIMEOUT_MS = 15 * 6e4;
function errMsg(e) {
  if (e instanceof Error) return e.message;
  return String(e);
}
function withTimeout(p, ms, what) {
  return new Promise((resolve, reject) => {
    const t = window.setTimeout(
      () => reject(new Error(`${what} \u8D85\u65F6\uFF08${Math.round(ms / 1e3)}s\uFF09`)),
      ms
    );
    p.then(
      (v) => {
        window.clearTimeout(t);
        resolve(v);
      },
      (e) => {
        window.clearTimeout(t);
        reject(e);
      }
    );
  });
}
function assertLoopbackUrl(raw) {
  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    throw new Error(`\u540E\u7AEF\u5730\u5740\u4E0D\u662F\u6709\u6548 URL\uFF1A${raw}`);
  }
  if (!["http:", "https:"].includes(parsed.protocol)) {
    throw new Error(`\u540E\u7AEF\u5730\u5740\u534F\u8BAE\u4E0D\u5141\u8BB8\uFF1A${parsed.protocol}`);
  }
  const host = parsed.hostname.toLowerCase();
  const loopback = host === "localhost" || host === "::1" || host.startsWith("127.");
  if (!loopback) {
    throw new Error(`\u4E3A\u907F\u514D\u6CC4\u9732 vault \u5185\u5BB9\uFF0CInstitute \u63D2\u4EF6\u53EA\u5141\u8BB8\u8FDE\u63A5\u672C\u673A\u56DE\u73AF\u5730\u5740\uFF1A${parsed.hostname}`);
  }
}
function exportSlug(text, maxLen = 80) {
  let s = String(text ?? "").trim().replace(/[\\/:*?"<>|#^[\]\u0000-\u001f]+/g, "-");
  s = s.replace(/\s+/g, " ");
  s = s.replace(/-{2,}/g, "-");
  s = s.replace(/^[ \-.]+|[ \-.]+$/g, "");
  s = s.slice(0, maxLen).replace(/^[ \-.]+|[ \-.]+$/g, "");
  return s || "untitled";
}
function fileSlug(text, maxLen = 40) {
  let s = (text || "").trim().replace(/[\\/:*?"<>|#^[\] -]+/g, "-");
  s = s.replace(/\s+/g, " ").replace(/-{2,}/g, "-").replace(/^[\s\-.]+|[\s\-.]+$/g, "");
  return s.slice(0, maxLen).replace(/^[\s\-.]+|[\s\-.]+$/g, "") || "untitled";
}
function todayStr() {
  const d = /* @__PURE__ */ new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}
function sgtDate(iso) {
  if (!iso) return null;
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return null;
  return new Date(t + 8 * 36e5).toISOString().slice(0, 10);
}
function fmtElapsed(iso) {
  const t = Date.parse(iso ?? "");
  if (Number.isNaN(t)) return "\u2014";
  let s = Math.max(0, Math.floor((Date.now() - t) / 1e3));
  const h = Math.floor(s / 3600);
  const m = Math.floor(s % 3600 / 60);
  s = s % 60;
  if (h > 0) return `${h}h${m}m`;
  if (m > 0) return `${m}m${s}s`;
  return `${s}s`;
}
function fmtCountdown(untilEpochS) {
  let s = Math.max(0, Math.round(untilEpochS - Date.now() / 1e3));
  const h = Math.floor(s / 3600);
  const m = Math.floor(s % 3600 / 60);
  s = s % 60;
  if (h > 0) return `${h}h${m}m`;
  if (m > 0) return `${m}m`;
  return `${s}s`;
}
function fmtClock(iso) {
  const t = Date.parse(iso ?? "");
  if (Number.isNaN(t)) return "--:--";
  const d = new Date(t);
  const pad = (n) => String(n).padStart(2, "0");
  return `${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function researchStatusZh(status) {
  const map = {
    pending: "\u5F85\u5904\u7406",
    running: "\u8FDB\u884C\u4E2D",
    completed: "\u5DF2\u5B8C\u6210",
    failed: "\u5931\u8D25",
    cancelled: "\u5DF2\u53D6\u6D88"
  };
  return map[status] ?? status;
}
function researchStatusIcon(status) {
  const map = {
    pending: "\u25CB",
    running: "\u25B6",
    completed: "\u2713",
    failed: "\u2717",
    cancelled: "\u2298"
  };
  return map[status] ?? "\xB7";
}
var InstituteApi = class {
  constructor(getBaseUrl) {
    this.getBaseUrl = getBaseUrl;
  }
  baseUrl() {
    const url = this.getBaseUrl().replace(/\/+$/, "");
    assertLoopbackUrl(url);
    return url;
  }
  /** JSON request with a hard timeout (default 10s). Never uses fetch. */
  async request(path, opts = {}) {
    const method = opts.method ?? "GET";
    const url = this.baseUrl() + path;
    const resp = await withTimeout(
      (0, import_obsidian.requestUrl)({
        url,
        method,
        contentType: opts.body !== void 0 ? "application/json" : void 0,
        body: opts.body !== void 0 ? JSON.stringify(opts.body) : void 0,
        throw: false
      }),
      opts.timeoutMs ?? DEFAULT_TIMEOUT_MS,
      `${method} ${path}`
    );
    if (resp.status >= 400) {
      let detail = "";
      try {
        detail = String(resp.json?.detail ?? resp.text ?? "");
      } catch {
        detail = resp.text ?? "";
      }
      throw new Error(`HTTP ${resp.status} \u2014 ${detail.slice(0, 300)}`);
    }
    return resp.json;
  }
  // ---- meta / status -----------------------------------------------------
  meta() {
    return this.request("/api/meta");
  }
  analysts() {
    return this.request("/api/analysts");
  }
  dailyStatus() {
    return this.request("/api/analysts/daily/status");
  }
  runAllDailies() {
    return this.request("/api/analysts/daily/run-now", { method: "POST" });
  }
  runAnalystDaily(analystId) {
    return this.request(`/api/analysts/${encodeURIComponent(analystId)}/daily/run`, {
      method: "POST"
    });
  }
  // ---- tasks ---------------------------------------------------------------
  listTasks(status, limit = 100) {
    return this.request(
      `/api/tasks?status=${encodeURIComponent(status)}&limit=${limit}`
    );
  }
  cancelTask(taskId) {
    return this.request(
      `/api/tasks/${encodeURIComponent(taskId)}/cancel`,
      { method: "POST" }
    );
  }
  ask(prompt, analystId) {
    return this.request("/api/ask", {
      method: "POST",
      body: { prompt, analyst_id: analystId || null },
      timeoutMs: ASK_TIMEOUT_MS
    });
  }
  // ---- research --------------------------------------------------------------
  researchQueue(status, limit = 100) {
    const q = status ? `?status=${encodeURIComponent(status)}&limit=${limit}` : `?limit=${limit}`;
    return this.request(`/api/research/queue${q}`);
  }
  enqueueResearch(topic) {
    return this.request("/api/research/queue", {
      method: "POST",
      body: { topic }
    });
  }
  exportResearch(queueId) {
    return this.request(
      `/api/vault/export/research/${encodeURIComponent(queueId)}`,
      { method: "POST" }
    );
  }
  // ---- whiteboard / mailbox / archive -----------------------------------------
  addWhiteboardTopic(topic, question = "") {
    return this.request("/api/whiteboard/topics", {
      method: "POST",
      body: { topic, question }
    });
  }
  createMailThread(subject, analystId, body) {
    return this.request("/api/mailbox/threads", {
      method: "POST",
      body: { subject, analyst_id: analystId, body }
    });
  }
  archiveSearch(q, limit = 15) {
    return this.request(
      `/api/archive/search?q=${encodeURIComponent(q)}&limit=${limit}`
    );
  }
  // ---- events ------------------------------------------------------------------
  events(since, limit, types) {
    const t = types ? `&types=${encodeURIComponent(types)}` : "";
    return this.request(`/api/events?since=${since}&limit=${limit}${t}`);
  }
  // ---- vault ---------------------------------------------------------------------
  vaultDoctor() {
    return this.request("/api/vault/doctor", { method: "POST" });
  }
  vaultIndex(state, limit = 200) {
    return this.request(
      `/api/vault/index?state=${encodeURIComponent(state)}&limit=${limit}`
    );
  }
};

// src/dashboard.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_DASHBOARD = "institute-dashboard";
var EVENT_LABELS = {
  "task.completed": "\u4EFB\u52A1\u5B8C\u6210",
  "task.failed": "\u4EFB\u52A1\u5931\u8D25",
  "task.cancelled": "\u4EFB\u52A1\u53D6\u6D88",
  "research.queued": "\u7814\u7A76\u6392\u961F",
  "research.completed": "\u6DF1\u5EA6\u7814\u7A76\u5B8C\u6210",
  "research.failed": "\u6DF1\u5EA6\u7814\u7A76\u5931\u8D25",
  "research.followups": "\u7814\u7A76\u8DDF\u8FDB",
  "whiteboard.board_opened": "\u767D\u677F\u5F00\u9898",
  "whiteboard.board_completed": "\u767D\u677F\u5B8C\u6210",
  "analyst_daily.completed": "\u5206\u6790\u5E08\u65E5\u62A5",
  "analyst_daily.failed": "\u5206\u6790\u5E08\u65E5\u62A5\u5931\u8D25",
  "analyst_daily.sweep_completed": "\u65E5\u62A5\u5168\u5458\u5B8C\u6210",
  "mailbox.reply": "\u4FE1\u7BB1\u56DE\u590D",
  "topic_pool.added": "\u8BAE\u9898\u5165\u6C60",
  "vault.conflict": "\u26A0\uFE0F \u4ED3\u5E93\u51B2\u7A81",
  "workflow.completed": "\u5DE5\u4F5C\u6D41\u5B8C\u6210",
  "workflow.failed": "\u5DE5\u4F5C\u6D41\u5931\u8D25",
  "workflow.cancelled": "\u5DE5\u4F5C\u6D41\u53D6\u6D88"
};
var EVENT_TYPES_FILTER = [
  "task.completed",
  "task.failed",
  "task.cancelled",
  "research.",
  "whiteboard.board_opened",
  "whiteboard.board_completed",
  "analyst_daily.",
  "mailbox.reply",
  "topic_pool.added",
  "vault.conflict",
  "workflow.completed",
  "workflow.failed",
  "workflow.cancelled"
].join(",");
var MAX_EVENTS_KEPT = 20;
var DAILY_STATUS_ZH = {
  completed: "\u5DF2\u5B8C\u6210",
  failed: "\u5931\u8D25",
  pending: "\u5F85\u8FD0\u884C"
};
var InstituteDashboardView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.refreshing = false;
    // events cursor (durable ids from the backend events table)
    this.cursor = 0;
    this.bootstrapped = false;
    this.events = [];
    this.plugin = plugin;
    this.navigation = false;
  }
  getViewType() {
    return VIEW_TYPE_DASHBOARD;
  }
  getDisplayText() {
    return "Institute \u4EEA\u8868\u76D8";
  }
  getIcon() {
    return "gauge";
  }
  async onOpen() {
    const root = this.contentEl;
    root.empty();
    root.style.padding = "8px 12px";
    root.style.fontSize = "13px";
    this.bannerEl = root.createDiv();
    this.bannerEl.style.display = "none";
    this.bannerEl.style.padding = "6px 10px";
    this.bannerEl.style.marginBottom = "8px";
    this.bannerEl.style.borderRadius = "6px";
    this.bannerEl.style.background = "rgba(var(--color-red-rgb), 0.15)";
    this.bannerEl.style.color = "var(--text-error)";
    this.bannerEl.style.fontWeight = "600";
    this.headerEl = root.createDiv();
    this.headerEl.style.marginBottom = "10px";
    this.headerEl.setText("\u72B6\u6001\uFF1A\u8FDE\u63A5\u4E2D\u2026");
    this.queueEl = this.section(root, "\u961F\u5217");
    this.handsEl = this.section(root, "\u6267\u884C\u624B");
    this.dailyEl = this.section(root, "\u4ECA\u65E5\u65E5\u62A5");
    this.runningEl = this.section(root, "\u8FDB\u884C\u4E2D");
    this.eventsEl = this.section(root, "\u6700\u8FD1\u4E8B\u4EF6");
    const actions = root.createDiv();
    actions.style.display = "flex";
    actions.style.gap = "8px";
    actions.style.marginTop = "12px";
    actions.style.flexWrap = "wrap";
    this.actionButton(actions, "\u63D0\u95EE", () => this.plugin.openAskModal());
    this.actionButton(actions, "\u6DF1\u5EA6\u7814\u7A76", () => this.plugin.openResearchPrompt());
    this.actionButton(actions, "\u6253\u5F00\u64CD\u4F5C\u53F0", () => this.plugin.openOperatorUi());
    void this.refresh();
    const everyMs = Math.max(5, this.plugin.settings.pollIntervalS || 10) * 1e3;
    this.registerInterval(window.setInterval(() => void this.refresh(), everyMs));
  }
  async onClose() {
    this.contentEl.empty();
  }
  // ---- skeleton helpers ----------------------------------------------------
  section(root, title) {
    const wrap = root.createDiv();
    wrap.style.marginBottom = "12px";
    const h = wrap.createDiv({ text: title });
    h.style.fontWeight = "600";
    h.style.fontSize = "11px";
    h.style.letterSpacing = "0.05em";
    h.style.color = "var(--text-muted)";
    h.style.marginBottom = "4px";
    return wrap.createDiv();
  }
  actionButton(parent, text, onClick) {
    const btn = parent.createEl("button", { text });
    btn.addEventListener("click", onClick);
  }
  chip(parent, text, color, title) {
    const s = parent.createSpan({ text });
    s.style.display = "inline-block";
    s.style.border = "1px solid";
    s.style.borderRadius = "10px";
    s.style.padding = "0 8px";
    s.style.margin = "0 6px 4px 0";
    s.style.fontSize = "12px";
    s.style.color = color;
    s.setAttribute("aria-label", title);
    s.setAttribute("title", title);
  }
  // ---- polling ---------------------------------------------------------------
  async refresh() {
    if (this.refreshing) return;
    this.refreshing = true;
    try {
      let meta;
      try {
        meta = await this.plugin.api.meta();
      } catch (e) {
        this.bannerEl.style.display = "block";
        this.bannerEl.setText(
          `\u65E0\u6CD5\u8FDE\u63A5\u540E\u7AEF ${this.plugin.api.baseUrl()} \u2014 ${errMsg(e)}`
        );
        this.headerEl.setText("\u72B6\u6001\uFF1A\u79BB\u7EBF");
        return;
      }
      this.bannerEl.style.display = "none";
      this.renderHeader(meta);
      this.renderQueue(meta);
      this.renderHands(meta.hands ?? []);
      try {
        await this.plugin.getRoster();
      } catch {
      }
      const [daily, running, queued] = await Promise.all([
        this.plugin.api.dailyStatus().catch(() => null),
        this.plugin.api.listTasks("running").catch(() => []),
        this.plugin.api.listTasks("queued").catch(() => [])
      ]);
      this.renderDaily(daily);
      this.renderRunning(running, queued);
      try {
        await this.pollEvents();
      } catch {
      }
      this.renderEvents();
    } finally {
      this.refreshing = false;
    }
  }
  // ---- 状态 / 队列 / 执行手 -----------------------------------------------------
  renderHeader(meta) {
    this.headerEl.empty();
    const dot = this.headerEl.createSpan({ text: "\u25CF " });
    dot.style.color = "var(--color-green)";
    this.headerEl.createSpan({
      text: `Institute One v${meta.version ?? "?"} \xB7 ${meta.work_date ?? "?"}`
    });
    if (meta.vault_configured === false) {
      const warn = this.headerEl.createSpan({ text: "\uFF08vault \u672A\u914D\u7F6E\uFF09" });
      warn.style.color = "var(--color-orange)";
    }
  }
  renderQueue(meta) {
    this.queueEl.empty();
    const by = meta.queue?.by_status ?? {};
    const running = by["running"] ?? 0;
    const queued = by["queued"] ?? 0;
    const completed = by["completed"] ?? 0;
    this.queueEl.setText(`\u8FD0\u884C ${running} \xB7 \u6392\u961F ${queued} \xB7 \u5DF2\u5B8C\u6210 ${completed}`);
  }
  renderHands(hands) {
    this.handsEl.empty();
    if (!hands.length) {
      this.muted(this.handsEl, "\uFF08\u65E0\u6267\u884C\u624B\uFF09");
      return;
    }
    const rank = (h) => {
      if (h.cooldown_until) return 1;
      if (h.degraded) return 2;
      if (h.available) return 0;
      return 3;
    };
    for (const h of [...hands].sort((a, b) => rank(a) - rank(b))) {
      if (h.cooldown_until) {
        this.chip(
          this.handsEl,
          `${h.name} \u23F3${fmtCountdown(h.cooldown_until)}`,
          "var(--color-orange)",
          `\u51B7\u5374\u4E2D\uFF1A${h.cooldown_reason ?? "rate limit"}`
        );
      } else if (h.degraded) {
        this.chip(
          this.handsEl,
          h.name,
          "var(--color-red)",
          `\u5DF2\u964D\u7EA7\uFF08\u8FDE\u7EED\u5931\u8D25 ${h.consecutive_failures} \u6B21\uFF09`
        );
      } else if (h.available) {
        this.chip(this.handsEl, h.name, "var(--color-green)", "\u53EF\u7528");
      } else {
        this.chip(
          this.handsEl,
          h.name,
          "var(--text-muted)",
          h.installed ? "\u4E0D\u53EF\u7528" : "\u672A\u5B89\u88C5"
        );
      }
    }
  }
  // ---- 今日日报 -------------------------------------------------------------------
  renderDaily(status) {
    this.dailyEl.empty();
    if (!status) {
      this.muted(this.dailyEl, "\uFF08\u65E0\u6CD5\u83B7\u53D6\u65E5\u62A5\u72B6\u6001\uFF09");
      return;
    }
    const entries = Object.entries(status.analysts ?? {});
    const done = entries.filter(([, s]) => s === "completed").length;
    const head = this.dailyEl.createDiv();
    head.style.display = "flex";
    head.style.alignItems = "center";
    head.style.gap = "8px";
    head.createSpan({ text: `${done}/${entries.length} \u5B8C\u6210` });
    const btn = head.createEl("button", { text: "\u8FD0\u884C\u5168\u5458\u65E5\u62A5" });
    btn.style.fontSize = "11px";
    btn.style.padding = "0 6px";
    btn.addEventListener("click", () => void this.runAllDailies());
    const dots = this.dailyEl.createDiv();
    dots.style.marginTop = "4px";
    for (const [id, s] of entries) {
      const a = this.plugin.analystById(id);
      const mark = s === "completed" ? "\u2713" : s === "failed" ? "\u2717" : "\u25CB";
      const span = dots.createSpan({ text: mark });
      span.style.marginRight = "6px";
      span.style.color = s === "completed" ? "var(--color-green)" : s === "failed" ? "var(--color-red)" : "var(--text-muted)";
      const who = a ? `${a.emoji} ${a.name}` : id;
      span.setAttribute("title", `${who} \xB7 ${DAILY_STATUS_ZH[s] ?? s}`);
      span.setAttribute("aria-label", `${who} \xB7 ${DAILY_STATUS_ZH[s] ?? s}`);
      if (s === "completed") {
        span.style.cursor = "pointer";
        span.addEventListener(
          "click",
          () => void this.plugin.openAnalystDailyNote(id, status.date)
        );
      }
    }
  }
  async runAllDailies() {
    try {
      await this.plugin.api.runAllDailies();
      new import_obsidian2.Notice("Institute: \u5DF2\u542F\u52A8\u5168\u5458\u65E5\u62A5\uFF08\u540E\u53F0\u8FD0\u884C\uFF0C\u5B8C\u6210\u540E\u81EA\u52A8\u5BFC\u51FA\uFF09\u3002", 6e3);
    } catch (e) {
      new import_obsidian2.Notice(`Institute: \u542F\u52A8\u5168\u5458\u65E5\u62A5\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  // ---- 进行中 --------------------------------------------------------------------
  renderRunning(running, queued) {
    this.runningEl.empty();
    const rows = [...running, ...queued];
    if (!rows.length) {
      this.muted(this.runningEl, "\uFF08\u6682\u65E0\u8FD0\u884C\u4E2D\u6216\u6392\u961F\u7684\u4EFB\u52A1\uFF09");
      return;
    }
    for (const t of rows.slice(0, 12)) {
      const line = this.runningEl.createDiv();
      line.style.display = "flex";
      line.style.alignItems = "center";
      line.style.gap = "6px";
      line.style.padding = "1px 0";
      const icon = t.status === "running" ? "\u25B6" : "\u23F8";
      const hand = t.hand ?? t.requested_hand ?? "?";
      const since = t.status === "running" ? t.started_at ?? t.created_at : t.created_at;
      const label = line.createSpan({
        text: `${icon} ${t.source} \xB7 ${hand} \xB7 ${fmtElapsed(since)}`
      });
      label.style.flex = "1";
      label.setAttribute("title", `\u4EFB\u52A1 ${t.id}\uFF08${t.status}\uFF09`);
      const cancel = line.createEl("button", { text: "\u2715" });
      cancel.style.fontSize = "10px";
      cancel.style.padding = "0 5px";
      cancel.setAttribute("title", "\u53D6\u6D88\u4EFB\u52A1");
      cancel.addEventListener("click", () => void this.cancelTask(t.id));
    }
    if (rows.length > 12) {
      this.muted(this.runningEl, `\u2026 \u8FD8\u6709 ${rows.length - 12} \u4E2A\u4EFB\u52A1`);
    }
  }
  async cancelTask(taskId) {
    try {
      const res = await this.plugin.api.cancelTask(taskId);
      new import_obsidian2.Notice(
        res.cancelled ? `Institute: \u5DF2\u53D6\u6D88\u4EFB\u52A1 ${taskId}\u3002` : `Institute: \u4EFB\u52A1 ${taskId} \u65E0\u6CD5\u53D6\u6D88\uFF08\u53EF\u80FD\u5DF2\u7ED3\u675F\uFF09\u3002`,
        5e3
      );
      void this.refresh();
    } catch (e) {
      new import_obsidian2.Notice(`Institute: \u53D6\u6D88\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  // ---- 最近事件 --------------------------------------------------------------------
  async pollEvents() {
    if (!this.bootstrapped) {
      for (let i = 0; i < 40; i++) {
        const page2 = await this.plugin.api.events(this.cursor, 200, EVENT_TYPES_FILTER);
        if (!page2.length) break;
        this.cursor = page2[page2.length - 1].id;
        this.pushEvents(page2);
        if (page2.length < 200) break;
      }
      this.bootstrapped = true;
      return;
    }
    const page = await this.plugin.api.events(this.cursor, 30, EVENT_TYPES_FILTER);
    if (page.length) {
      this.cursor = page[page.length - 1].id;
      this.pushEvents(page);
    }
  }
  /** Append an ascending page; keep the feed newest-first and capped. */
  pushEvents(page) {
    const interesting = page.filter((e) => EVENT_LABELS[e.type] !== void 0);
    if (!interesting.length) return;
    this.events = [...interesting.reverse(), ...this.events].slice(0, MAX_EVENTS_KEPT);
  }
  renderEvents() {
    this.eventsEl.empty();
    if (!this.events.length) {
      this.muted(this.eventsEl, "\uFF08\u6682\u65E0\u4E8B\u4EF6\uFF09");
      return;
    }
    for (const e of this.events) {
      const line = this.eventsEl.createDiv();
      line.style.display = "flex";
      line.style.alignItems = "baseline";
      line.style.gap = "6px";
      line.style.padding = "1px 0";
      const time = line.createSpan({ text: fmtClock(e.created_at) });
      time.style.color = "var(--text-muted)";
      time.style.fontSize = "11px";
      line.createSpan({ text: EVENT_LABELS[e.type] ?? e.type });
      const detail = this.eventDetail(e);
      if (detail) {
        const d = line.createSpan({
          text: detail.length > 36 ? detail.slice(0, 36) + "\u2026" : detail
        });
        d.style.color = "var(--text-muted)";
        d.style.flex = "1";
        d.style.overflow = "hidden";
        d.style.whiteSpace = "nowrap";
        d.style.textOverflow = "ellipsis";
        d.setAttribute("title", detail);
      }
      if (this.canOpenNote(e)) {
        const link = line.createSpan({ text: "\u6253\u5F00\u7B14\u8BB0" });
        link.style.color = "var(--text-accent)";
        link.style.cursor = "pointer";
        link.style.fontSize = "11px";
        link.style.whiteSpace = "nowrap";
        link.addEventListener("click", () => void this.openEventNote(e));
      }
    }
  }
  eventDetail(e) {
    const p = e.payload ?? {};
    if (e.type.startsWith("analyst_daily.") && e.ref_id) {
      const a = this.plugin.analystById(e.ref_id);
      return a ? `${a.emoji} ${a.name}` : e.ref_id;
    }
    const topic = p["topic"] ?? p["subject"];
    if (typeof topic === "string" && topic) return topic;
    return e.ref_id ?? "";
  }
  canOpenNote(e) {
    return e.type === "research.completed" || e.type === "analyst_daily.completed" || e.type === "whiteboard.board_completed";
  }
  async openEventNote(e) {
    const p = e.payload ?? {};
    const date = sgtDate(e.created_at);
    if (e.type === "research.completed") {
      await this.plugin.openResearchNote(String(p["topic"] ?? e.ref_id ?? ""), date);
    } else if (e.type === "analyst_daily.completed") {
      await this.plugin.openAnalystDailyNote(e.ref_id, String(p["date"] ?? date ?? ""));
    } else if (e.type === "whiteboard.board_completed") {
      await this.plugin.openWhiteboardNote(String(p["topic"] ?? e.ref_id ?? ""), date);
    }
  }
  // ---- misc -----------------------------------------------------------------------
  muted(parent, text) {
    const el = parent.createDiv({ text });
    el.style.color = "var(--text-muted)";
  }
};

// src/modals.ts
var import_obsidian3 = require("obsidian");
var AskModal = class extends import_obsidian3.Modal {
  constructor(plugin, initialPrompt, editor) {
    super(plugin.app);
    this.plugin = plugin;
    this.editor = editor;
    this.analyst = null;
    this.roster = [];
    this.prompt = initialPrompt;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText("\u63D0\u95EE (Ask the Institute)");
    new import_obsidian3.Setting(contentEl).setName("\u5206\u6790\u5E08").setDesc("\u4EE5\u54EA\u4F4D\u5206\u6790\u5E08\u7684\u4EBA\u683C\u56DE\u7B54\uFF08\u6765\u81EA\u540E\u7AEF\u540D\u518C\uFF0C\u8BB0\u4F4F\u4E0A\u6B21\u9009\u62E9\uFF09\u3002").addDropdown((dd) => {
      dd.addOption("", "\uFF08\u9ED8\u8BA4\u6267\u884C\u624B\uFF0C\u65E0\u4EBA\u683C\uFF09");
      dd.onChange((v) => {
        this.analyst = this.roster.find((a) => a.id === v) ?? null;
      });
      void this.plugin.getRoster().then((roster) => {
        this.roster = roster;
        for (const a of roster) {
          dd.addOption(a.id, `${a.emoji} ${a.name}\uFF08${a.name_en}\uFF09\u2014 ${a.focus}`);
        }
        const last = this.plugin.settings.defaultAnalyst;
        if (last && roster.some((a) => a.id === last)) {
          dd.setValue(last);
          this.analyst = roster.find((a) => a.id === last) ?? null;
        }
      }).catch((e) => {
        new import_obsidian3.Notice(`Institute: \u65E0\u6CD5\u52A0\u8F7D\u5206\u6790\u5E08\u540D\u518C \u2014 ${errMsg(e)}`, 6e3);
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u95EE\u9898").setDesc("\u5DF2\u9884\u586B\u5F53\u524D\u9009\u4E2D\u6587\u672C\uFF08\u5982\u6709\uFF09\u3002Cmd/Ctrl+Enter \u63D0\u4EA4\u3002").addTextArea((ta) => {
      ta.setValue(this.prompt);
      ta.setPlaceholder("\u60F3\u8BA9\u7814\u7A76\u6240\u7814\u7A76\u4EC0\u4E48\uFF1F");
      ta.onChange((v) => this.prompt = v);
      ta.inputEl.rows = 8;
      ta.inputEl.style.width = "100%";
      ta.inputEl.addEventListener("keydown", (ev) => {
        if ((ev.metaKey || ev.ctrlKey) && ev.key === "Enter") {
          ev.preventDefault();
          this.submit();
        }
      });
      window.setTimeout(() => ta.inputEl.focus(), 0);
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u63D0\u95EE").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    const prompt = this.prompt.trim();
    if (!prompt) {
      new import_obsidian3.Notice("Institute: \u95EE\u9898\u4E3A\u7A7A\u3002");
      return;
    }
    this.close();
    this.plugin.settings.defaultAnalyst = this.analyst?.id ?? "";
    void this.plugin.saveSettings();
    void this.plugin.runAsk(prompt, this.analyst, this.editor);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PromptModal = class extends import_obsidian3.Modal {
  constructor(app, title, placeholder, onSubmit) {
    super(app);
    this.title = title;
    this.placeholder = placeholder;
    this.onSubmit = onSubmit;
    this.value = "";
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText(this.title);
    new import_obsidian3.Setting(contentEl).setName("\u5185\u5BB9").addText((t) => {
      t.setPlaceholder(this.placeholder);
      t.onChange((v) => this.value = v);
      t.inputEl.style.width = "100%";
      t.inputEl.addEventListener("keydown", (ev) => {
        if (ev.key === "Enter") {
          ev.preventDefault();
          this.submit();
        }
      });
      window.setTimeout(() => t.inputEl.focus(), 0);
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u63D0\u4EA4").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    const value = this.value.trim();
    if (!value) {
      new import_obsidian3.Notice("Institute: \u5185\u5BB9\u4E3A\u7A7A\u3002");
      return;
    }
    this.close();
    this.onSubmit(value);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PickModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, items, toText, onPick, placeholder = "") {
    super(app);
    this.items = items;
    this.toText = toText;
    this.onPick = onPick;
    if (placeholder) this.setPlaceholder(placeholder);
  }
  getItems() {
    return this.items;
  }
  getItemText(item) {
    return this.toText(item);
  }
  onChooseItem(item) {
    this.onPick(item);
  }
};
var MailModal = class extends import_obsidian3.Modal {
  constructor(plugin, initialBody) {
    super(plugin.app);
    this.plugin = plugin;
    this.subject = "";
    this.body = initialBody;
    this.analystId = plugin.settings.defaultAnalyst;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText("\u5199\u4FE1\u7ED9\u5206\u6790\u5E08");
    new import_obsidian3.Setting(contentEl).setName("\u6536\u4EF6\u4EBA").setDesc("\u4FE1\u4EF6\u4F1A\u5F00\u4E00\u4E2A\u4FE1\u7BB1\u4F1A\u8BDD\uFF0C\u5206\u6790\u5E08\u5728\u540E\u53F0\u56DE\u590D\u3002").addDropdown((dd) => {
      dd.addOption("", "\uFF08\u9009\u62E9\u5206\u6790\u5E08\uFF09");
      dd.onChange((v) => this.analystId = v);
      void this.plugin.getRoster().then((roster) => {
        for (const a of roster) {
          dd.addOption(a.id, `${a.emoji} ${a.name}\uFF08${a.name_en}\uFF09`);
        }
        if (this.analystId && roster.some((a) => a.id === this.analystId)) {
          dd.setValue(this.analystId);
        } else {
          this.analystId = "";
        }
      }).catch((e) => {
        new import_obsidian3.Notice(`Institute: \u65E0\u6CD5\u52A0\u8F7D\u5206\u6790\u5E08\u540D\u518C \u2014 ${errMsg(e)}`, 6e3);
      });
    });
    new import_obsidian3.Setting(contentEl).setName("\u4E3B\u9898").addText((t) => {
      t.setPlaceholder("\u4FE1\u4EF6\u4E3B\u9898\u2026");
      t.onChange((v) => this.subject = v);
      t.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).setName("\u6B63\u6587").setDesc("\u5DF2\u9884\u586B\u5F53\u524D\u9009\u4E2D\u6587\u672C\uFF08\u5982\u6709\uFF09\u3002").addTextArea((ta) => {
      ta.setValue(this.body);
      ta.setPlaceholder("\u60F3\u95EE\u4EC0\u4E48\u3001\u60F3\u8BA9\u5BF9\u65B9\u6838\u5B9E\u4EC0\u4E48\u2026");
      ta.onChange((v) => this.body = v);
      ta.inputEl.rows = 8;
      ta.inputEl.style.width = "100%";
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (b) => b.setButtonText("\u53D1\u9001").setCta().onClick(() => this.submit())
    );
  }
  submit() {
    if (!this.analystId) {
      new import_obsidian3.Notice("Institute: \u8BF7\u9009\u62E9\u5206\u6790\u5E08\u3002");
      return;
    }
    if (!this.subject.trim()) {
      new import_obsidian3.Notice("Institute: \u8BF7\u586B\u5199\u4E3B\u9898\u3002");
      return;
    }
    if (!this.body.trim()) {
      new import_obsidian3.Notice("Institute: \u8BF7\u586B\u5199\u6B63\u6587\u3002");
      return;
    }
    this.close();
    void this.send();
  }
  async send() {
    try {
      await this.plugin.api.createMailThread(
        this.subject.trim(),
        this.analystId,
        this.body.trim()
      );
      new import_obsidian3.Notice("Institute: \u5DF2\u53D1\u9001\uFF0C\u56DE\u590D\u5C06\u51FA\u73B0\u5728\u64CD\u4F5C\u53F0\u4FE1\u7BB1\u3002", 6e3);
    } catch (e) {
      new import_obsidian3.Notice(`Institute: \u53D1\u9001\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var DOCTOR_LABELS = [
  ["total", "\u603B\u8BA1"],
  ["clean", "\u6E05\u6D01"],
  ["conflict", "\u51B2\u7A81"],
  ["missing", "\u7F3A\u5931"],
  ["drifted", "\u6F02\u79FB"]
];
var VaultDoctorModal = class extends import_obsidian3.Modal {
  constructor(plugin, report, conflicts) {
    super(plugin.app);
    this.plugin = plugin;
    this.report = report;
    this.conflicts = conflicts;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText("\u4ED3\u5E93\u4F53\u68C0 (vault doctor)");
    const table = contentEl.createEl("table");
    table.style.width = "100%";
    table.style.borderCollapse = "collapse";
    for (const [key, label] of DOCTOR_LABELS) {
      const tr = table.createEl("tr");
      const td1 = tr.createEl("td", { text: label });
      td1.style.padding = "2px 12px 2px 0";
      td1.style.color = "var(--text-muted)";
      const value = this.report[key] ?? 0;
      const td2 = tr.createEl("td", { text: String(value) });
      td2.style.padding = "2px 0";
      if (key === "conflict" && value > 0) td2.style.color = "var(--color-orange)";
      if ((key === "missing" || key === "drifted") && value > 0) {
        td2.style.color = "var(--color-red)";
      }
    }
    if (this.conflicts.length > 0) {
      const h = contentEl.createEl("h5", {
        text: "\u51B2\u7A81\u7B14\u8BB0\uFF08\u4EBA\u5DE5\u7F16\u8F91\u8FC7\uFF0C\u540E\u7AEF\u5DF2\u53E6\u5B58\u300Cinstitute update\u300D\u526F\u672C\uFF09"
      });
      h.style.marginBottom = "6px";
      for (const row of this.conflicts) {
        const line = contentEl.createDiv();
        line.style.display = "flex";
        line.style.alignItems = "center";
        line.style.gap = "8px";
        line.style.padding = "2px 0";
        const path = line.createSpan({ text: row.path });
        path.style.flex = "1";
        path.style.fontSize = "12px";
        path.style.wordBreak = "break-all";
        const btn = line.createEl("button", { text: "\u6253\u5F00" });
        btn.addEventListener("click", () => {
          this.close();
          void this.plugin.openVaultRel(row.path);
        });
      }
    } else if ((this.report["conflict"] ?? 0) === 0) {
      const ok = contentEl.createDiv({ text: "\u6CA1\u6709\u51B2\u7A81\u7B14\u8BB0\u3002" });
      ok.style.color = "var(--text-muted)";
      ok.style.marginTop = "8px";
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  baseUrl: "http://127.0.0.1:8110",
  vaultSubfolder: "Institute",
  defaultAnalyst: "",
  insertStyle: "callout",
  pollIntervalS: 10
};
var InstituteOnePlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.roster = null;
    this.rosterAt = 0;
  }
  async onload() {
    await this.loadSettings();
    this.api = new InstituteApi(() => this.settings.baseUrl);
    this.addSettingTab(new InstituteSettingTab(this.app, this));
    this.registerView(VIEW_TYPE_DASHBOARD, (leaf) => new InstituteDashboardView(leaf, this));
    this.addRibbonIcon("gauge", "Institute \u4EEA\u8868\u76D8", () => void this.activateDashboard());
    this.addCommand({
      id: "open-dashboard",
      name: "Institute: \u6253\u5F00\u4EEA\u8868\u76D8",
      callback: () => void this.activateDashboard()
    });
    this.addCommand({
      id: "ask",
      name: "Institute: \u63D0\u95EE (Ask)",
      callback: () => this.openAskModal()
    });
    this.addCommand({
      id: "queue-research",
      name: "Institute: \u6DF1\u5EA6\u7814\u7A76",
      callback: () => this.openResearchPrompt()
    });
    this.addCommand({
      id: "research-queue-status",
      name: "Institute: \u7814\u7A76\u961F\u5217\u72B6\u6001",
      callback: () => void this.showResearchQueue()
    });
    this.addCommand({
      id: "whiteboard-topic",
      name: "Institute: \u52A0\u5165\u767D\u677F\u8BAE\u9898",
      callback: () => this.openWhiteboardCommand()
    });
    this.addCommand({
      id: "export-research",
      name: "Institute: \u5BFC\u51FA\u7814\u7A76\u62A5\u544A\u5230\u4ED3\u5E93",
      callback: () => void this.exportResearchCommand()
    });
    this.addCommand({
      id: "vault-doctor",
      name: "Institute: \u4ED3\u5E93\u4F53\u68C0 (vault doctor)",
      callback: () => void this.vaultDoctorCommand()
    });
    this.addCommand({
      id: "mailbox-compose",
      name: "Institute: \u5199\u4FE1\u7ED9\u5206\u6790\u5E08",
      callback: () => {
        const selection = this.app.workspace.activeEditor?.editor?.getSelection() ?? "";
        new MailModal(this, selection).open();
      }
    });
    this.addCommand({
      id: "archive-search",
      name: "Institute: \u68C0\u7D22\u7814\u7A76\u6863\u6848",
      callback: () => {
        const editor = this.app.workspace.activeEditor?.editor ?? null;
        new PromptModal(
          this.app,
          "\u68C0\u7D22\u7814\u7A76\u6863\u6848",
          "\u5173\u952E\u8BCD\u2026",
          (q) => void this.searchArchive(q, editor)
        ).open();
      }
    });
    this.addCommand({
      id: "run-analyst-daily",
      name: "Institute: \u8FD0\u884C\u67D0\u4F4D\u5206\u6790\u5E08\u65E5\u62A5",
      callback: () => void this.runAnalystDailyCommand()
    });
    this.addCommand({
      id: "open-operator-ui",
      name: "Institute: \u6253\u5F00\u64CD\u4F5C\u53F0 (web)",
      callback: () => this.openOperatorUi()
    });
    this.statusBar = this.addStatusBarItem();
    this.statusBar.addClass("mod-clickable");
    this.statusBar.setText("\u2699\uFE0E inst: \u2026");
    this.statusBar.onClickEvent(() => void this.activateDashboard());
    void this.refreshStatus();
    this.registerInterval(
      window.setInterval(() => void this.refreshStatus(), 6e4)
    );
  }
  openOperatorUi() {
    window.open(this.settings.baseUrl);
  }
  // ---- dashboard ----------------------------------------------------------
  async activateDashboard() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD);
    if (existing.length > 0) {
      await workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (!leaf) return;
    await leaf.setViewState({ type: VIEW_TYPE_DASHBOARD, active: true });
    await workspace.revealLeaf(leaf);
  }
  // ---- roster cache ----------------------------------------------------------
  async getRoster(maxAgeMs = 10 * 6e4) {
    const now = Date.now();
    if (this.roster && now - this.rosterAt < maxAgeMs) return this.roster;
    this.roster = await this.api.analysts();
    this.rosterAt = now;
    return this.roster;
  }
  /** Sync lookup against the cached roster (may miss before the first fetch). */
  analystById(id) {
    return this.roster?.find((a) => a.id === id) ?? null;
  }
  // ---- 提问 (Ask) ----------------------------------------------------------------
  openAskModal() {
    const editor = this.app.workspace.activeEditor?.editor ?? null;
    const selection = editor?.getSelection() ?? "";
    new AskModal(this, selection, editor).open();
  }
  async runAsk(prompt, analyst, editor) {
    prompt = prompt.trim();
    if (!prompt) {
      new import_obsidian4.Notice("Institute: \u95EE\u9898\u4E3A\u7A7A\u3002");
      return;
    }
    const who = analyst ? `${analyst.emoji} ${analyst.name}` : "Institute";
    const started = Date.now();
    const notice = new import_obsidian4.Notice(`Institute: ${who} \u601D\u8003\u4E2D\u2026 0s`, 0);
    const tick = window.setInterval(() => {
      const s = Math.round((Date.now() - started) / 1e3);
      notice.setMessage(`Institute: ${who} \u601D\u8003\u4E2D\u2026 ${s}s`);
    }, 1e3);
    try {
      const task = await this.api.ask(prompt, analyst?.id ?? null);
      const out = (task.output ?? "").trim();
      let text;
      if (!out) {
        text = task.error ? `> [!failure] \u4EFB\u52A1 ${task.id} ${task.status}
> ${task.error}` : `\uFF08\u4EFB\u52A1 ${task.id} ${task.status}\uFF1A\u65E0\u8F93\u51FA\uFF09`;
      } else if (this.settings.insertStyle === "callout") {
        const header = `> [!quote] ${who} \xB7 ${todayStr()}`;
        text = header + "\n" + out.split("\n").map((l) => `> ${l}`).join("\n");
      } else {
        text = out;
      }
      if (editor) {
        const cursor = editor.getCursor("to");
        const lineEnd = { line: cursor.line, ch: editor.getLine(cursor.line).length };
        editor.replaceRange(`

${text}
`, lineEnd);
      } else {
        await this.createAskNote(prompt, analyst, text);
      }
      const s = Math.round((Date.now() - started) / 1e3);
      notice.setMessage(`Institute: \u5B8C\u6210\uFF08\u4EFB\u52A1 ${task.id}\uFF0C${task.status}\uFF0C${s}s\uFF09\u3002`);
      window.setTimeout(() => notice.hide(), 5e3);
    } catch (e) {
      notice.hide();
      new import_obsidian4.Notice(`Institute: \u63D0\u95EE\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    } finally {
      window.clearInterval(tick);
    }
  }
  async createAskNote(prompt, analyst, output) {
    const folder = "Ask";
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      try {
        await this.app.vault.createFolder(folder);
      } catch {
      }
    }
    const base = `${todayStr()} ${fileSlug(prompt)}`;
    let path = (0, import_obsidian4.normalizePath)(`${folder}/${base}.md`);
    let n = 1;
    while (this.app.vault.getAbstractFileByPath(path)) {
      path = (0, import_obsidian4.normalizePath)(`${folder}/${base} ${++n}.md`);
    }
    const quoted = prompt.replace(/\n/g, "\n> ");
    const header = analyst ? `> [!question] \u63D0\u95EE\uFF08\u5206\u6790\u5E08\uFF1A${analyst.emoji} ${analyst.name}\uFF09` : "> [!question] \u63D0\u95EE";
    const file = await this.app.vault.create(
      path,
      `${header}
> ${quoted}

${output}
`
    );
    await this.app.workspace.getLeaf(true).openFile(file);
  }
  // ---- 深度研究 -----------------------------------------------------------------
  openResearchPrompt() {
    const sel = this.app.workspace.activeEditor?.editor?.getSelection()?.trim();
    if (sel) {
      void this.queueResearch(sel);
    } else {
      new PromptModal(
        this.app,
        "\u6DF1\u5EA6\u7814\u7A76",
        "\u7814\u7A76\u4E3B\u9898\u2026",
        (topic) => void this.queueResearch(topic)
      ).open();
    }
  }
  async queueResearch(topic) {
    topic = topic.trim();
    if (!topic) {
      new import_obsidian4.Notice("Institute: \u4E3B\u9898\u4E3A\u7A7A\u3002");
      return;
    }
    try {
      const res = await this.api.enqueueResearch(topic);
      if (res.refused === "cooldown") {
        new import_obsidian4.Notice(
          `Institute: \u300C${topic}\u300D\u88AB\u62D2 \u2014 \u51B7\u5374\u4E2D\uFF08\u4E0A\u6B21\u5B8C\u6210\u4E8E ${res.last_completed_at ?? "\u6700\u8FD1"}\uFF09\u3002`,
          8e3
        );
      } else if (res.deduped) {
        new import_obsidian4.Notice(
          `Institute: \u300C${topic}\u300D\u5DF2\u5728\u961F\u5217\u4E2D\uFF08\u72B6\u6001\uFF1A${researchStatusZh(res.status ?? "pending")}\uFF0Cid\uFF1A${res.id ?? "?"}\uFF09\u3002`,
          8e3
        );
      } else {
        new import_obsidian4.Notice(
          `Institute: \u5DF2\u6392\u961F\u6DF1\u5EA6\u7814\u7A76\u300C${topic}\u300D\uFF08id\uFF1A${res.id ?? "?"}\uFF09\u3002\u5B8C\u6210\u540E\u53EF\u5728\u4EEA\u8868\u76D8\u6253\u5F00\u62A5\u544A\u3002`,
          6e3
        );
      }
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u6DF1\u5EA6\u7814\u7A76\u6392\u961F\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  async showResearchQueue() {
    let items;
    try {
      items = await this.api.researchQueue();
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u65E0\u6CD5\u83B7\u53D6\u7814\u7A76\u961F\u5217 \u2014 ${errMsg(e)}`, 8e3);
      return;
    }
    if (!items.length) {
      new import_obsidian4.Notice("Institute: \u7814\u7A76\u961F\u5217\u4E3A\u7A7A\u3002");
      return;
    }
    new PickModal(
      this.app,
      items,
      (it) => {
        const date = sgtDate(it.finished_at) ?? sgtDate(it.created_at) ?? "";
        return `${researchStatusIcon(it.status)} ${it.topic} \xB7 ${researchStatusZh(it.status)}${date ? ` \xB7 ${date}` : ""}`;
      },
      (it) => {
        if (it.status === "completed") {
          void this.openResearchNote(it.topic, sgtDate(it.finished_at));
        } else {
          new import_obsidian4.Notice(
            `Institute: \u300C${it.topic}\u300D\u72B6\u6001\uFF1A${researchStatusZh(it.status)}${it.error ? ` \u2014 ${it.error.slice(0, 120)}` : ""}`,
            6e3
          );
        }
      },
      "\u9009\u62E9\u7814\u7A76\u6761\u76EE\uFF08\u5DF2\u5B8C\u6210\u7684\u4F1A\u6253\u5F00\u62A5\u544A\u7B14\u8BB0\uFF09\u2026"
    ).open();
  }
  // ---- 白板 ------------------------------------------------------------------------
  openWhiteboardCommand() {
    const info = this.app.workspace.activeEditor;
    const editor = info?.editor ?? null;
    const file = info?.file ?? null;
    const sel = editor?.getSelection()?.trim() ?? "";
    if (file) {
      const question = sel || (editor ? firstContentLine(editor.getValue()) : "");
      void this.addWhiteboardTopic(file.basename, question);
    } else if (sel) {
      void this.addWhiteboardTopic(sel, "");
    } else {
      new PromptModal(
        this.app,
        "\u52A0\u5165\u767D\u677F\u8BAE\u9898",
        "\u8BAE\u9898\u2026",
        (topic) => void this.addWhiteboardTopic(topic, "")
      ).open();
    }
  }
  async addWhiteboardTopic(topic, question) {
    topic = topic.trim();
    if (!topic) {
      new import_obsidian4.Notice("Institute: \u8BAE\u9898\u4E3A\u7A7A\u3002");
      return;
    }
    try {
      const row = await this.api.addWhiteboardTopic(topic, question.trim());
      new import_obsidian4.Notice(
        `Institute: \u300C${topic}\u300D\u5DF2\u52A0\u5165\u767D\u677F\u8BAE\u9898\u6C60\uFF08#${row.id ?? "?"}\uFF0C\u72B6\u6001\uFF1A${row.status ?? "pending"}\uFF09\u3002`,
        6e3
      );
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u52A0\u5165\u8BAE\u9898\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  // ---- 导出研究 / 仓库体检 -----------------------------------------------------------
  async exportResearchCommand() {
    let items;
    try {
      items = await this.api.researchQueue("completed");
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u65E0\u6CD5\u83B7\u53D6\u5DF2\u5B8C\u6210\u7814\u7A76 \u2014 ${errMsg(e)}`, 8e3);
      return;
    }
    if (!items.length) {
      new import_obsidian4.Notice("Institute: \u6CA1\u6709\u5DF2\u5B8C\u6210\u7684\u7814\u7A76\u53EF\u5BFC\u51FA\u3002");
      return;
    }
    new PickModal(
      this.app,
      items,
      (it) => `${it.topic} \xB7 ${sgtDate(it.finished_at) ?? "?"}`,
      (it) => void this.doExportResearch(it),
      "\u9009\u62E9\u8981\u5BFC\u51FA\u5230\u4ED3\u5E93\u7684\u7814\u7A76\u2026"
    ).open();
  }
  async doExportResearch(item) {
    const notice = new import_obsidian4.Notice(`Institute: \u6B63\u5728\u5BFC\u51FA\u300C${item.topic}\u300D\u2026`, 0);
    try {
      const res = await this.api.exportResearch(item.id);
      notice.hide();
      new import_obsidian4.Notice(`Institute: \u5DF2\u5BFC\u51FA ${res.exported}`, 6e3);
      await this.openVaultRel(res.exported);
    } catch (e) {
      notice.hide();
      new import_obsidian4.Notice(`Institute: \u5BFC\u51FA\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  async vaultDoctorCommand() {
    const notice = new import_obsidian4.Notice("Institute: \u4ED3\u5E93\u4F53\u68C0\u4E2D\u2026", 0);
    let report;
    try {
      report = await this.api.vaultDoctor();
    } catch (e) {
      notice.hide();
      new import_obsidian4.Notice(`Institute: \u4F53\u68C0\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
      return;
    }
    let conflicts = [];
    if ((report["conflict"] ?? 0) > 0) {
      try {
        conflicts = await this.api.vaultIndex("conflict");
      } catch {
      }
    }
    notice.hide();
    new VaultDoctorModal(this, report, conflicts).open();
  }
  // ---- 检索研究档案 ----------------------------------------------------------------
  async searchArchive(query, editor) {
    let hits;
    try {
      hits = await this.api.archiveSearch(query, 15);
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u68C0\u7D22\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
      return;
    }
    if (!hits.length) {
      new import_obsidian4.Notice(`Institute: \u6CA1\u6709\u627E\u5230\u4E0E\u300C${query}\u300D\u76F8\u5173\u7684\u6863\u6848\u3002`, 6e3);
      return;
    }
    const plain = (s) => s.replace(/<\/?b>/g, "").replace(/\s+/g, " ").trim();
    new PickModal(
      this.app,
      hits,
      (h) => `${plain(h.snippet)} \u2014 ${h.path}`,
      (h) => {
        if (!editor) {
          new import_obsidian4.Notice("Institute: \u6CA1\u6709\u6D3B\u52A8\u7684\u7F16\u8F91\u5668\uFF0C\u65E0\u6CD5\u63D2\u5165\u5F15\u7528\u3002", 6e3);
          return;
        }
        const text = `> \u5F15\u7528\uFF1A${plain(h.snippet)}
> \u2014 institute archive: ${h.path}
`;
        editor.replaceRange(text, editor.getCursor());
      },
      "\u9009\u62E9\u8981\u5F15\u7528\u7684\u6863\u6848\u7247\u6BB5\u2026"
    ).open();
  }
  // ---- 运行某位分析师日报 ------------------------------------------------------------
  async runAnalystDailyCommand() {
    let roster;
    let marks = {};
    try {
      roster = await this.getRoster();
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u65E0\u6CD5\u52A0\u8F7D\u5206\u6790\u5E08\u540D\u518C \u2014 ${errMsg(e)}`, 8e3);
      return;
    }
    try {
      marks = (await this.api.dailyStatus()).analysts ?? {};
    } catch {
    }
    const items = roster.filter((a) => a.category !== "ops");
    if (!items.length) {
      new import_obsidian4.Notice("Institute: \u540D\u518C\u4E2D\u6CA1\u6709\u53EF\u8FD0\u884C\u65E5\u62A5\u7684\u5206\u6790\u5E08\u3002");
      return;
    }
    const mark = (id) => {
      const s = marks[id];
      return s === "completed" ? "\u2713" : s === "failed" ? "\u2717" : "\u25CB";
    };
    new PickModal(
      this.app,
      items,
      (a) => `${mark(a.id)} ${a.emoji} ${a.name}\uFF08${a.id}\uFF09\u2014 ${a.focus}`,
      (a) => void this.runOneDaily(a),
      "\u9009\u62E9\u5206\u6790\u5E08\uFF08\u2713 \u4ECA\u65E5\u5DF2\u5B8C\u6210 / \u25CB \u5F85\u8FD0\u884C\uFF09\u2026"
    ).open();
  }
  async runOneDaily(a) {
    try {
      await this.api.runAnalystDaily(a.id);
      new import_obsidian4.Notice(
        `Institute: \u5DF2\u542F\u52A8 ${a.emoji} ${a.name} \u7684\u65E5\u62A5\uFF08\u540E\u53F0\u8FD0\u884C\uFF0C\u5B8C\u6210\u540E\u81EA\u52A8\u5BFC\u51FA\uFF09\u3002`,
        6e3
      );
    } catch (e) {
      new import_obsidian4.Notice(`Institute: \u542F\u52A8\u65E5\u62A5\u5931\u8D25 \u2014 ${errMsg(e)}`, 8e3);
    }
  }
  // ---- vault note opening -------------------------------------------------------------
  // The backend exports notes RELATIVE to its vault_dir; settings.vaultSubfolder
  // maps that root into this Obsidian vault (default "Institute").
  subPath(rel) {
    const sub = this.settings.vaultSubfolder.trim().replace(/^\/+|\/+$/g, "");
    return (0, import_obsidian4.normalizePath)(sub ? `${sub}/${rel}` : rel);
  }
  async openFileAt(path) {
    const f = this.app.vault.getAbstractFileByPath((0, import_obsidian4.normalizePath)(path));
    if (f instanceof import_obsidian4.TFile) {
      await this.app.workspace.getLeaf().openFile(f);
      return true;
    }
    return false;
  }
  /**
   * Fallback: list the folder and open the best (name-descending) markdown
   * file containing every fragment. With fallbackAny, a topic-specific folder
   * may fall back to its newest file when fragments don't match.
   */
  async openBestMatch(folderRel, fragments, fallbackAny = false) {
    const folder = this.app.vault.getAbstractFileByPath(
      (0, import_obsidian4.normalizePath)(this.subPath(folderRel))
    );
    if (!(folder instanceof import_obsidian4.TFolder)) return false;
    const files = folder.children.filter(
      (c) => c instanceof import_obsidian4.TFile && c.extension === "md"
    );
    let pool = files.filter((f) => fragments.every((s) => s && f.name.includes(s)));
    if (!pool.length && fallbackAny) pool = files;
    if (!pool.length) return false;
    pool.sort((a, b) => b.name.localeCompare(a.name));
    await this.app.workspace.getLeaf().openFile(pool[0]);
    return true;
  }
  async openVaultRel(rel) {
    if (await this.openFileAt(this.subPath(rel))) return;
    new import_obsidian4.Notice(
      `Institute: \u5728 vault \u4E2D\u627E\u4E0D\u5230 ${this.subPath(rel)} \u2014 \u8BF7\u68C0\u67E5\u300CVault \u5B50\u76EE\u5F55\u300D\u8BBE\u7F6E\u3002`,
      7e3
    );
  }
  async openResearchNote(topic, date) {
    const folder = `Research/${exportSlug(topic)}`;
    if (date && await this.openFileAt(this.subPath(`${folder}/${date} \u6DF1\u5EA6\u62A5\u544A.md`))) return;
    if (await this.openBestMatch(folder, ["\u6DF1\u5EA6\u62A5\u544A"], true)) return;
    new import_obsidian4.Notice("Institute: \u7B14\u8BB0\u5C1A\u672A\u5BFC\u51FA\u3002", 5e3);
  }
  async openAnalystDailyNote(analystId, date) {
    const folder = `Analysts/${exportSlug(analystId)}`;
    if (date && await this.openFileAt(this.subPath(`${folder}/${date} \u65E5\u62A5.md`))) return;
    if (await this.openBestMatch(folder, date ? [date] : ["\u65E5\u62A5"], true)) return;
    new import_obsidian4.Notice("Institute: \u7B14\u8BB0\u5C1A\u672A\u5BFC\u51FA\u3002", 5e3);
  }
  async openWhiteboardNote(topic, date) {
    const slug = exportSlug(topic);
    if (date && await this.openFileAt(this.subPath(`Whiteboard/${date} ${slug}.md`))) return;
    if (await this.openBestMatch("Whiteboard", [slug.slice(0, 16)])) return;
    new import_obsidian4.Notice("Institute: \u7B14\u8BB0\u5C1A\u672A\u5BFC\u51FA\u3002", 5e3);
  }
  // ---- Status bar ----------------------------------------------------------
  async refreshStatus() {
    try {
      const meta = await this.api.meta();
      const by = meta.queue?.by_status ?? {};
      const running = by["running"] ?? 0;
      const queued = by["queued"] ?? 0;
      let dailyTxt = "";
      try {
        const ds = await this.api.dailyStatus();
        const vals = Object.values(ds.analysts ?? {});
        const done = vals.filter((v) => v === "completed").length;
        if (vals.length > 0 && done < vals.length) dailyTxt = ` \xB7\u65E5\u62A5${done}/${vals.length}`;
      } catch {
      }
      this.statusBar.setText(`\u2699\uFE0E inst: ${running}\u8FD0\u884C/${queued}\u6392\u961F${dailyTxt}`);
      this.statusBar.style.color = "";
      this.statusBar.setAttribute(
        "aria-label",
        `Institute One v${meta.version ?? "?"} @ ${this.settings.baseUrl} \u2014 \u70B9\u51FB\u6253\u5F00\u4EEA\u8868\u76D8`
      );
    } catch {
      this.statusBar.setText("\u2717 inst");
      this.statusBar.style.color = "var(--text-error)";
      this.statusBar.setAttribute(
        "aria-label",
        `Institute One \u65E0\u6CD5\u8FDE\u63A5\uFF08${this.settings.baseUrl}\uFF09\u2014 \u70B9\u51FB\u6253\u5F00\u4EEA\u8868\u76D8`
      );
    }
  }
  // ---- settings io ------------------------------------------------------
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!Number.isFinite(this.settings.pollIntervalS) || this.settings.pollIntervalS < 5) {
      this.settings.pollIntervalS = DEFAULT_SETTINGS.pollIntervalS;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
function firstContentLine(body) {
  let lines = body.split("\n");
  if (lines[0]?.trim() === "---") {
    const end = lines.findIndex((l, i) => i > 0 && l.trim() === "---");
    if (end > 0) lines = lines.slice(end + 1);
  }
  for (const raw of lines) {
    const line = raw.replace(/^#+\s*/, "").replace(/^>\s*/, "").trim();
    if (line) return line.slice(0, 200);
  }
  return "";
}
var InstituteSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("\u540E\u7AEF\u5730\u5740 (base URL)").setDesc("Institute One \u540E\u7AEF\u8FD0\u884C\u7684\u5730\u5740\u3002").addText(
      (t) => t.setPlaceholder(DEFAULT_SETTINGS.baseUrl).setValue(this.plugin.settings.baseUrl).onChange(async (v) => {
        this.plugin.settings.baseUrl = v.trim().replace(/\/+$/, "") || DEFAULT_SETTINGS.baseUrl;
        await this.plugin.saveSettings();
        void this.plugin.refreshStatus();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Vault \u5B50\u76EE\u5F55").setDesc(
      "\u540E\u7AEF\u5BFC\u51FA\u7B14\u8BB0\u6240\u5728\u7684 vault \u5B50\u76EE\u5F55\uFF08\u5BF9\u5E94\u540E\u7AEF\u7684 vault_dir\uFF09\u3002\u7559\u7A7A\u8868\u793A vault \u6839\u76EE\u5F55\u3002"
    ).addText(
      (t) => t.setPlaceholder(DEFAULT_SETTINGS.vaultSubfolder).setValue(this.plugin.settings.vaultSubfolder).onChange(async (v) => {
        this.plugin.settings.vaultSubfolder = v.trim().replace(/^\/+|\/+$/g, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("\u9ED8\u8BA4\u5206\u6790\u5E08").setDesc("\u63D0\u95EE/\u5199\u4FE1\u65F6\u9884\u9009\u7684\u5206\u6790\u5E08\uFF08\u63D0\u95EE\u540E\u4F1A\u81EA\u52A8\u8BB0\u4F4F\u4E0A\u6B21\u9009\u62E9\uFF09\u3002").addDropdown((dd) => {
      dd.addOption("", "\uFF08\u9ED8\u8BA4\u6267\u884C\u624B\uFF0C\u65E0\u4EBA\u683C\uFF09");
      dd.setValue("");
      dd.onChange(async (v) => {
        this.plugin.settings.defaultAnalyst = v;
        await this.plugin.saveSettings();
      });
      void this.plugin.getRoster().then((roster) => {
        for (const a of roster) {
          dd.addOption(a.id, `${a.emoji} ${a.name}\uFF08${a.name_en}\uFF09`);
        }
        if (roster.some((a) => a.id === this.plugin.settings.defaultAnalyst)) {
          dd.setValue(this.plugin.settings.defaultAnalyst);
        }
      }).catch(() => {
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u56DE\u7B54\u63D2\u5165\u6837\u5F0F").setDesc("\u63D0\u95EE\u7684\u56DE\u7B54\u4EE5 callout \u5F15\u7528\u5757\u8FD8\u662F\u7EAF\u6587\u672C\u63D2\u5165\u3002").addDropdown((dd) => {
      dd.addOption("callout", "Callout \u5F15\u7528\u5757\uFF08\u63A8\u8350\uFF09");
      dd.addOption("plain", "\u7EAF\u6587\u672C");
      dd.setValue(this.plugin.settings.insertStyle);
      dd.onChange(async (v) => {
        this.plugin.settings.insertStyle = v === "plain" ? "plain" : "callout";
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("\u4EEA\u8868\u76D8\u8F6E\u8BE2\u95F4\u9694\uFF08\u79D2\uFF09").setDesc("\u4EEA\u8868\u76D8\u53EF\u89C1\u65F6\u7684\u81EA\u52A8\u5237\u65B0\u95F4\u9694\uFF0C\u6700\u5C0F 5 \u79D2\u3002\u91CD\u65B0\u6253\u5F00\u4EEA\u8868\u76D8\u540E\u751F\u6548\u3002").addText(
      (t) => t.setPlaceholder(String(DEFAULT_SETTINGS.pollIntervalS)).setValue(String(this.plugin.settings.pollIntervalS)).onChange(async (v) => {
        const n = parseInt(v, 10);
        this.plugin.settings.pollIntervalS = Number.isFinite(n) ? Math.max(5, n) : DEFAULT_SETTINGS.pollIntervalS;
        await this.plugin.saveSettings();
      })
    );
    const sub = this.plugin.settings.vaultSubfolder || "(vault \u6839\u76EE\u5F55)";
    const desc = document.createDocumentFragment();
    desc.appendText(`\u53EA\u8BFB\u8BF4\u660E\uFF1A\u540E\u7AEF\u628A\u5B8C\u6210\u7684\u5DE5\u4F5C\u5BFC\u51FA\u5230\u300C${sub}\u300D\u4E0B\uFF0C\u5E03\u5C40\u5982\u4E0B\uFF1A`);
    const ul = desc.createEl("ul");
    for (const line of [
      "Research/<\u4E3B\u9898>/<\u65E5\u671F> \u6DF1\u5EA6\u62A5\u544A.md \u2014 \u6DF1\u5EA6\u7814\u7A76\u62A5\u544A",
      "Briefing/<\u65E5\u671F> \u6668\u4F1A\u7B80\u62A5.md \u2014 \u6668\u4F1A\u7B80\u62A5",
      "Daily/<\u65E5\u671F> \u6BCF\u65E5\u65E5\u62A5.md \u2014 \u6BCF\u65E5\u65E5\u62A5",
      "Analysts/<\u5206\u6790\u5E08>/<\u65E5\u671F> \u65E5\u62A5.md \u2014 \u5206\u6790\u5E08\u89C2\u5BDF\u65E5\u62A5",
      "Whiteboard/<\u65E5\u671F> <\u4E3B\u9898>.md \u2014 \u767D\u677F\uFF08\u6BCF\u4F4D\u5206\u6790\u5E08\u4E00\u8282\uFF09",
      "Ask/<\u65E5\u671F> <\u63D0\u95EE>.md \u2014 \u672C\u63D2\u4EF6\u5728\u65E0\u7F16\u8F91\u5668\u65F6\u521B\u5EFA\uFF08\u5728 vault \u6839\u76EE\u5F55\uFF09"
    ]) {
      ul.createEl("li", { text: line });
    }
    new import_obsidian4.Setting(containerEl).setName("Vault \u7B14\u8BB0\u5E03\u5C40").setDesc(desc).setDisabled(true);
  }
};
